### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [OakesLab/AFT-Alignment_by_Fourier_Transform#3]
Hi @stemarcotti ,

that's a fantastic tool, thanks for sharing! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by stemarcotti** [comment]
Hi Robert!
Thanks for raising the issue - an MIT license has now been added to the repo.
All the best, 
Stefania

**Comment by haesleinhuepf** [comment]
Awesome, thank you!
